config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :skip => [:sessions, :registration]

  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  filter :locale, exclude: /^\/users\/auth\/facebook/
  
  resources :transactions, only: [:index] do
    member do
      put :approve
      put :reject
    end
  end

  resources :users, only: [:index, :show] do
    resources :transactions, controller: 'users/transactions', only: [:new, :create]
  end
  
  get '/sitemap' => "transactions#sitemap", :as => :sitemap
  root "transactions#home"
  get "/:id" => "users#show", as: :user_by_permalink

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :transactions_from, class_name: "Transaction", foreign_key: "from_user_id"
  has_many :transactions_to, class_name: "Transaction", foreign_key: "to_user_id"
  
  validates_uniqueness_of :permalink, allow_nil: true
  # Permalink cannot be a number, so it can't be confused with the id
  validates_format_of :permalink, :with => /[^\d]+/, allow_nil: true
  before_save :clean_permalink

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.image = auth.info.image
    end
  end

  def self.with_transactions
    where("id IN (SELECT DISTINCT from_user_id FROM transactions) OR id IN (SELECT DISTINCT to_user_id FROM transactions)")
  end

  def to_param
    (self.permalink && self.permalink.parameterize) || (self.name && "#{self.id}-#{self.name.parameterize}") || self.id
  end

  def set_locale(new_locale)
    if self.locale != new_locale
      self.update locale: new_locale
    end
  end

  def balance
    sum_from = self.transactions_from.with_state(:approved).sum(:value)
    sum_to = self.transactions_to.with_state(:approved).sum(:value)
    sum_to - sum_from
  end

  private

  def clean_permalink
    self.permalink = self.permalink.gsub(/[^0-9a-z]/i, '').downcase if self.permalink
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to :root
    end
  end

end

app/controllers/users/transactions_controller.rb
class Users::TransactionsController < ApplicationController

  before_action :set_user

  respond_to :html

  after_action :verify_authorized, except: %i[]
  after_action :verify_policy_scoped, only: %i[]
  before_action :authenticate_user!, only: %i[new]

  def new    
    @transaction = @user.transactions_to.new
    @transaction.from_user = current_user
    @transaction.value = params[:value].to_i
    authorize @transaction
    respond_with @transaction
  end

  def create
    @transaction = @user.transactions_to.new(transaction_params)
    @transaction.from_user = current_user
    authorize @transaction
    @transaction.save
    respond_with @transaction, location: -> { user_by_permalink_path(@user) }
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def transaction_params
    params.require(:transaction).permit(*policy(@transaction || Transaction.new).permitted_attributes)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show]

  respond_to :html

  after_action :verify_authorized, except: %i[index]
  after_action :verify_policy_scoped, only: %i[index]

  def index
    @users = policy_scope(User).order(:name)
    respond_with @users    
  end

  def show
    authorize @user
    unless request.path.match(/\A\/#{params[:locale]}\/#{@user.to_param}(\.\w+)?\z/)
      format = request.format.symbol
      return redirect_to user_by_permalink_path("#{@user.to_param}#{".#{format}" unless format == :html}")
    end
    @transactions = Transaction.involving(@user).with_state(:approved).order("updated_at DESC")
    if policy(@user).update?
      # This will instantiate UserDecorator for the users
      @pending = Transaction.involving(@user).with_state(:pending).order("updated_at DESC")
      @pending_from = @pending.map &:from_user
      @pending_to = @pending.map &:to_user
    else
      @pending = nil
    end
    # This will instantiate UserDecorator for the users
    @from_users = @transactions.map &:from_user
    @to_users = @transactions.map &:to_user
    respond_with @user
  end

  private

  def set_user
    @user ||= User.find_by_permalink(params[:id])
    @user ||= User.find(params[:id])
  end

end

app/views/users/_balance.html.slim
h1
  = @user.status_label(@transactions.exists?)
h2
  span.number= @user.balance_with_sign
  = " #{@user.balance_label}"

app/views/users/_user.html.slim
article.user
  .image
    = link_to user.display_image, user_by_permalink_path(user)
    span= link_to user.name.truncate(24), user_by_permalink_path(user)

app/views/users/index.html.slim
- content_for :title do
  = User.model_name.human.pluralize
article
  - if @users.exists?
    section.users
      = render @users

app/views/users/show.html.slim
- suppress_headline_and_article!
- content_for :title do
  == @user.name
- content_for :meta_tags do
  meta name="description" content="#{@user.status_label(@transactions.exists?)[0..-2]} #{@user.balance} #{@user.balance_label}."
  meta name="keywords" content="#{@user.name} Sistêmico"
  meta property="og:title" content="#{@user.name} · Sistêmico"
  meta property="og:type" content="website"
  meta property="og:url" content=user_by_permalink_url(@user)
  meta property="og:image" content=(@user.image.present? ? "#{@user.image}?height=256&width=256" : "#{request.protocol}#{request.host_with_port}#{image_path("logo_facebook.png")}")
  meta property="og:description" content="#{@user.status_label(@transactions.exists?)[0..-2]} #{@user.balance} #{@user.balance_label}."
  meta name="author" content=@user.name
- content_for :header do
  section.user_profile
    .image
      .avatar= @user.display_image
      .facebook= link_to image_tag("facebook.png", alt: "@user.name"), "https://www.facebook.com/#{@user.uid}", target: :_blank
- content_for :post_header do
  - if @user.balance == 0 && @transactions.exists?
    section.status.balanced= render 'balance'
  - elsif @user.balance == 0 && !@transactions.exists?
    section.status.inactive= render 'balance'
  - else
    section.status.unbalanced= render 'balance'
- if @user == current_user
  article.pending_transactions
    section.transactions.pending
      h2
        span.number= "#{@pending.count} "
        - if @transactions.count == 1
          = t('transactions.singular')
        - else
          = t('transactions.plural')
        = " #{t('transactions.pending').pluralize(@pending.count)}"
      - if @pending.exists?
        = render partial: 'transactions/transaction', collection: @pending, locals: { show_events: true }
- else
  article.send
    = link_to t('users.send', user: @user.name), new_user_transaction_path(@user.id), class: "button"
    p.tip= t('users.show.no_positive_balance_needed')

article.confirmed_transactions
  section.transactions
    h2
      span.number= "#{@transactions.count} "
      - if @transactions.count == 1
        = t('transactions.singular')
      - else
        = t('transactions.plural')
      = " #{t('transactions.confirmed').pluralize(@transactions.count)}"
    - if @transactions.exists?
      = render @transactions