config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :skip => [:sessions, :registration]

  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  filter :locale, exclude: /^\/users\/auth\/facebook/
  
  resources :transactions, only: [:index] do
    member do
      put :approve
      put :reject
    end
  end

  resources :users, only: [:index, :show] do
    resources :transactions, controller: 'users/transactions', only: [:new, :create]
  end
  
  get '/sitemap' => "transactions#sitemap", :as => :sitemap
  root "transactions#home"
  get "/:id" => "users#show", as: :user_by_permalink

end

app/controllers/transactions_controller.rb
class TransactionsController < StateController

  before_action :set_transaction, only: [:approve, :reject]

  respond_to :html, except: [:sitemap]
  respond_to :xml, only: [:sitemap]

  after_action :verify_authorized, except: %i[home index sitemap]
  after_action :verify_policy_scoped, only: %i[home index sitemap]

  def home
    @transactions = policy_scope(Transaction).with_state(:approved).order("updated_at DESC").limit(3)
    @users = policy_scope(User).order("updated_at DESC").limit(12)
    # This will instantiate UserDecorator for the users
    @from_users = @transactions.map &:from_user
    @to_users = @transactions.map &:to_user
    respond_with @transactions
  end

  def index
    @transactions = policy_scope(Transaction).with_state(:approved).order("updated_at DESC")
    # This will instantiate UserDecorator for the users
    @from_users = @transactions.map &:from_user
    @to_users = @transactions.map &:to_user
    respond_with @transactions
  end

  def sitemap
    @users = policy_scope(User).with_transactions.order("updated_at DESC")
    respond_with @users
  end

  def approve
    transition_state(@transaction, :approve, user_by_permalink_path(@transaction.to_user))
  end

  def reject
    transition_state(@transaction, :reject, user_by_permalink_path(@transaction.to_user))
  end

  private

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

end

app/controllers/users/transactions_controller.rb
class Users::TransactionsController < ApplicationController

  before_action :set_user

  respond_to :html

  after_action :verify_authorized, except: %i[]
  after_action :verify_policy_scoped, only: %i[]
  before_action :authenticate_user!, only: %i[new]

  def new    
    @transaction = @user.transactions_to.new
    @transaction.from_user = current_user
    @transaction.value = params[:value].to_i
    authorize @transaction
    respond_with @transaction
  end

  def create
    @transaction = @user.transactions_to.new(transaction_params)
    @transaction.from_user = current_user
    authorize @transaction
    @transaction.save
    respond_with @transaction, location: -> { user_by_permalink_path(@user) }
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def transaction_params
    params.require(:transaction).permit(*policy(@transaction || Transaction.new).permitted_attributes)
  end

end

app/views/transactions/_transaction.html.slim
article.transaction
  .from_user
    h5
      = link_to transaction.from_user.name, user_by_permalink_path(transaction.from_user)
      span= " #{t('transfered')}"
  .transaction_images
    .from= link_to transaction.from_user.display_image, user_by_permalink_path(transaction.from_user)
    .to= link_to transaction.to_user.display_image, user_by_permalink_path(transaction.to_user)
  .value
    span.number= "#{transaction.value} "
    = t('activerecord.attributes.user.balance').pluralize(transaction.value)
  .to_user
    h5
      span= "#{t('to')} "
      = link_to transaction.to_user.name, user_by_permalink_path(transaction.to_user)
  .description= transaction.description
  .created_at= "#{time_ago_in_words(transaction.created_at)} #{t('transactions.time_ago')}"
  / TODO confirm if pending trasactions will be listed here 
  / .status= transaction.human_state_name
  / TODO is it possible to output div.buttons only if at least one button exists?
  - if defined?(show_events) && show_events
    .buttons_group
      - if transaction.can_approve? && policy(transaction).approve?
        = link_to t('activerecord.state_machines.transaction.state.events.approve'), approve_transaction_path(transaction), method: :put, data: { confirm: t('confirm') }, class: 'button accept'
      - if transaction.can_reject? && policy(transaction).reject?
        = link_to t('activerecord.state_machines.transaction.state.events.reject'), reject_transaction_path(transaction), method: :put, data: { confirm: t('confirm') }, class: 'button reject'
      p.tip== t('users.show.transactions.warning')

app/views/transactions/home.html.slim
- suppress_headline_and_article!
- content_for :title do
  = t('.title')
- content_for :meta_tags do
  meta name="description" content="#{t('.h2')} #{t('.h3')} #{t('.h4')}"
  meta name="keywords" content="#{t('.h2')} #{t('.h3')} #{t('.h4')} Sistêmico"
  meta property="og:title" content="#{t('.title')} · Sistêmico"
  meta property="og:type" content="website"
  meta property="og:url" content=request.url
  meta property="og:image" content="#{request.protocol}#{request.host_with_port}#{image_path("logo_facebook.png")}"
  meta property="og:description" content="#{t('.h2')} #{t('.h3')} #{t('.h4')}"
  meta name="author" content="Oswaldo Oliveira"
- content_for :header do
  section
    h2= t('.h2')
    h3= t('.h3')
  - if !current_user
    section.login
      = link_to t('devise.shared.links.sign_in_with_provider', provider: 'Facebook'), user_omniauth_authorize_path(:facebook), class: 'button'
      h4= t('.h4')
- content_for :post_header do
  ul
    - ['safe', 'trust', 'free', 'digital'].each do |icon|
      li
        = image_tag "home_header_icons_#{icon}.png"
        p= t(".icons.#{icon}")
article
  - if @transactions.exists?
    section.transactions
      h3
        = t('.transactions')
        = " · "
        = link_to t('view_more'), transactions_path
      = render @transactions
  - if @users.exists?
    section.users
      h3
        = t('.users')
        = " · "
        = link_to t('view_more'), users_path
      div
        = render @users

app/views/transactions/index.html.slim
- content_for :title do
  = Transaction.model_name.human.pluralize
article
  - if @transactions.exists?
    section.transactions
      = render @transactions